<?php 	include( "20050114-d8c2.lib.php" ); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><!-- InstanceBegin template="/Templates/min_opp_menu_breadcrumb.dwt.php" codeOutsideHTMLIsLocked="false" -->
<head>
<script type="text/javascript"> <!--
    function UnCryptMailto( s )
    {
        var n = 0;
        var r = "";
        for( var i = 0; i < s.length; i++)
        {
            n = s.charCodeAt( i );
            if( n >= 8364 )
            {
                n = 128;
            }
            r += String.fromCharCode( n - 1 );
        }
        return r;
    }

    function linkTo_UnCryptMailto( s )
    {
        location.href=UnCryptMailto( s );
    }
// --> </script>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<!-- InstanceBeginEditable name="doctitle" -->
<title>Saint Louis Christian College</title>
<!-- InstanceEndEditable -->
<link href="../../includes/slcc.css" rel="stylesheet" type="text/css" />
<!-- InstanceBeginEditable name="head" --><!-- InstanceEndEditable -->
</head>

<body>
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" id="toptable">
	<tr bgcolor="#003974">
		<td class="header" align="center"><a href="/"><img src="../../images/homepage_header_banner.jpg" border="0"/></a></td>
	</tr>
</table>
<table width="100%" height="37" border="0" align="center" cellpadding="0" cellspacing="0">
	<tr>
		<td bgcolor="#003974">
			<?php include("../../includes/topmenu.inc"); ?>
		</td>
	</tr>
</table>
<table id="maintable" cellpadding="0" cellspacing="0" border="0">
	<tr class="content_top">
		<td class="blue_side_bar">&nbsp;</td>
		<td class="content_top_left">&nbsp;</td>
		<td class="content_middle">&nbsp;</td>
		<td class="content_top_right">&nbsp;</td>
		<td class="blue_side_bar">&nbsp;</td>
	</tr>
	<tr>
		<td class="content_white_side">
			<table cellpadding="0" cellspacing="0" border="0" id="tabletop">
				<tr class="content_blue_side">
					<td class="blue_side_bar">&nbsp;</td>
				</tr>
				<tr class="content_gray_side">
					<td class="gray_side_bar">&nbsp;</td>
				</tr>
			</table>		</td>
	  <td class="content_white_side_left">
			<table cellpadding="0" cellspacing="0" border="0">
				<tr class="content_blue_side">
					<td class="content_blue_side_left">&nbsp;</td>
				</tr>
				<tr class="content_gray_side">
					<td class="content_gray_side_left">&nbsp;</td>
				</tr>
			</table>		
	  </td>
	  <td rowspan="2" class="content">
	  	<table border="0" cellpadding="0" cellspacing="0">
			<tr>
				<td valign="top" rowspan="2">
					<table cellpadding="0" cellspacing="0" border="0" width="120">
						<tr>
							<td height="56"><a href="../newsearch.php"><img src="../../images/buttons/ministry/search_min_opp.jpg" border="0"/></a></td>
						</tr>
						<tr>
							<td height="56"><a href="../submit/"><img src="../../images/buttons/ministry/submit_min_opp.jpg" border="0"/></a></td>
						</tr>
						<tr>
							<td height="20">&nbsp;</td>
						</tr>
					</table>
				</td>
				<td valign="top">
					<table width="100%" height="16" border="0" cellpadding="0" cellspacing="0">
						<tr>
							<td width="10"></td>
							<td class="breadcrumb"><br /><script type="text/javascript" src="../../Scripts/MPBackLinks.js"></script><br /></td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td valign="top">
					<table cellpadding="0" cellspacing="0" border="0" width="675">
						<tr>
							<td width="10">&nbsp;</td>
							<td width="665">
				<!-- InstanceBeginEditable name="Main" -->
				<!-- ------------------------ Begin: Your FormMail's Description  ------------------------ -->
                          <!-- =======================  Begin: Form Generated By PHP FormMail Generator ======================= -->
                          <?php
	if( !$isHideForm ): 
		global $sErr ;
		if( $sErr ) print "<br><a name='error'></a><center><font class='form_error' >$sErr</font></center><br>"; 

		$starColor = $sErr ? "#ff0000" : "#000000";
		$style=" class='form_text' ";
 ?>
                      </h1>
                    <form name="frmFormMail" action="index.php" method='post' enctype='multipart/form-data'>
                          <input type='hidden' name='formmail_submit' value='Y'>
                          <input type='hidden' name='esh_formmail_subject' value="ministry opportunity submission">
                          <input type='hidden' name='esh_formmail_recipient' value="nbaker@slcconline.edu">
                          <input type='hidden' name='esh_formmail_cc' value="">
                          <input type='hidden' name='esh_formmail_bcc' value="">
                          <input type='hidden' name='esh_formmail_return_subject' value="Ministry Opportunity Submission">
                          <input type='hidden' name='esh_formmail_return_msg' value="Thank you for submitting your ministry opportunity to Saint Louis Christian College's Ministry Opportunities Database. This e-mail is to confirm your submission. You do not need to reply. 

-Saint Louis Christian College">
                          <input type='hidden' name='esh_formmail_mail_and_file' value="">
                          <input type='hidden' name='esh_formmail_charset' value="">
                          <em>This submission form is for leaders in churches, organizations, and groups to submit an entry to the Ministry Opportunities Database. Submitting an open position does not require a fee, however, we would appreciate notification  when the position is filled. </em>
						  <br />
						  <br />
						  <em>Disclaimer: Saint Louis Christian College cannot guarantee that all submissions will be added to the database. Submissions will be reviewed and approved on a case-by-case basis. If your submission is not added to the database within 5 business days, please send an e-mail to <a href="javascript:linkTo_UnCryptMailto('nbjmup;ocblfsAtmddpomjof/fev');">nbaker [at] slcconline [dot] edu</a>.
                          <br />
                          <br />
                          Your ministry listing will be active for 90 days, beginning on the day of submission. Prior to the end of these 90 days, you will be notified and given an opportunity to renew or remove your listing.
                          </em>
						  <br />
						  <br />
						  <em>*</em></span><em> Indicates a Required Field </em>
							<table width="665" height="10" border='0' cellpadding='5' cellspacing='0'  >
								<tr valign="top">
									<td height="3" colspan="3" align='right'>
										<div align="left">
											<font class="section_heading"><strong>Ministry Opportunity  Information </strong></font>
										</div>
									</td>
								</tr>
								<tr valign="top">
									<td align='right' width="190">Church Name:</td>
									<td aligh='right'><em>*</em></td>
									<td width="450"><input name="Church_Name" type="text" id="Church_Name"></td>
								</tr>
								<tr valign="top">
									<td align='right'>Address:</td>
									<td width='8' aligh='right'><em>*</em></td>
									<td><input type="text" name="Address" ></td>
								</tr>
								<tr valign="top">
									<td align='right'>City:</td>
									<td width='8'  aligh='right'><em>*</em></td>
									<td><input name="City" type="text" id="City" ></td>
								</tr>
								<tr valign="top">
									<td align='right'>State:</td>
									<td width='8' aligh='right'><em>*</em></td>
									<td><select name="State" id="State">
										<option value=All> All</option>
										<option value=AL> Alabama</option>
										<option value=AK> Alaska</option>
										<option value=AZ> Arizona</option>
										<option value=AR> Arkansas</option>
										<option value=CA> California</option>
										<option value=CO> Colorado</option>
										<option value=CT> Connecticut</option>
										<option value=DE> Delaware</option>
										<option value=FL> Florida</option>
										<option value=GA> Georgia</option>
										<option value=HI> Hawaii</option>
										<option value=ID> Idaho</option>
										<option value=IN> Indiana</option>
										<option value=IL> Illinois</option>
										<option value=IA> Iowa</option>
										<option value=KS> Kansas</option>
										<option value=KY> Kentucky</option>
										<option value=LA> Louisiana</option>
										<option value=ME> Maine</option>
										<option value=MD> Maryland</option>
										<option value=MA> Massachussets</option>
										<option value=MI> Michigan</option>
										<option value=MN> Minnesota</option>
										<option value=MS> Mississippi</option>
										<option value=MO> Missouri</option>
										<option value=MT> Montana</option>
										<option value=NE> Nebraska</option>
										<option value=NV> Nevada</option>
										<option value=NJ> New Jersey</option>
										<option value=NY> New York</option>
										<option value=NH> New Hampshire</option>
										<option value=NM> New Mexico</option>
										<option value=NC> North Carolina</option>
										<option value=ND> North Dakota</option>
										<option value=OH> Ohio</option>
										<option value=OK> Oklahoma</option>
										<option value=OR> Oregon</option>
										<option value=PA> Pennsylvania</option>
										<option value=RI> Rhode Island</option>
										<option value=SC> South Carolina</option>
										<option value=SD> South Dakota</option>
										<option value=TN> Tennessee</option>
										<option value=TX> Texas</option>
										<option value=UT> Utah</option>
										<option value=VA> Virginia</option>
										<option value=VT> Vermont</option>
										<option value=WA> Washington</option>
										<option value=WV> West Virginia</option>
										<option value=WI> Wisconsin</option>
										<option value=WY> Wyoming</option>
										</select>
									</td>
                          		</tr>
								<tr valign="top">
									<td align='right'>ZIP Code:</td>
									<td aligh='right'><em>*</em></td>
									<td><input name="zip" type="text" id="zip" size="11" maxlength="11" ></td>
								</tr>
								<tr valign="top">
									<td align='right'>Position Available: </td>
									<td aligh='right'><em>*</em></td>
									<td><input name="Position" type="text" id="Position"></td>
								</tr>
                                <tr valign="top">
                                	<td align='right'>Pay Type: </td>
                                    <td aligh='right'><em>*</em></td>
                                    <td><select name="PayType" id="PayType">
                                    	<option value=FT> Full-Time</option>
                                        <option value=PT> Part-Time</option>
                                        <option value=UN> Unspecified</option>
                                        </select>
                                    </td>
                                </tr>
								<tr valign="top">
									<td colspan="3" align='right'>
										<div align="left">
											<font class="section_heading">Contact Information</font>
										</div>
									</td>
								</tr>
								<tr valign="top">
									<td align='right'>Contact Name:</td>
									<td width='8' aligh='right'><em>*</em></td>
									<td><input name="Contact" type="text" id="Contact"></td>
								</tr>
								<tr valign="top">
									<td align='right'>Phone: </td>
									<td aligh='right'><em>*</em></td>
									<td><input name="Phone" type="text" id="Phone"></td>
								</tr>
								<tr valign="top">
									<td align='right'>E-mail Address:</td>
									<td aligh='right'><em>*</em></td>
									<td><input name="Email" type="text" id="Email"></td>
								</tr>
								<tr valign="top">
									<td align='right'>Website Address:</td>
									<td width='8' aligh='right'>&nbsp;</td>
									<td><input name="Website" type="text" id="Website"></td>
								</tr>
								<tr valign="top">
									<td colspan="3" align='right'>
										<div align="left">
											<font class="section_heading">Additional Information</font>
										</div>
									</td>
								</tr>
								<tr valign="top">
									<td align='right'>
										YOUR E-mail Address:
										<br />
										<br />
										(to confirm that this form<br />was submitted properly)
									</td>
									<td aligh='right'><em>*</em></td>
									<td><input name="Sender" type="sender's email" id="Sender"></td>
								</tr>
								<tr valign="top">
									<td align='right'>Instructions or Additional Info:</td>
									<td  aligh='right'>&nbsp;</td>
									<td><textarea name="Additional" cols="40" rows="5" id="Additional"></textarea></td>
								</tr>
								<tr valign="top" >
									<td height="3" colspan=3 align='center'><input type='submit' value='Submit' onclick='post'>
									&nbsp;&nbsp;
									<input type='button' value='Cancel' onclick="location.href='/';"></td>
								</tr>
							</table>
                      </form>
                      <!-- =======================  End:  ======================= -->
                      <?php
		if( $sErr ) print "<script language='javascript' type='text/javascript'>location.href='#error';</script>";;; 

else: //!$isHideForm
	print( "<br><br><hr><center><b>Your form has been sent. Thank you.</b><br><br><input type='button' value='Home' onclick=\"location.href='/';\"></center><br><br>" );
endif; //!$isHideForm
			?>
				<!-- InstanceEndEditable -->
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</td>
		<td class="content_white_side_right">
			<table cellpadding="0" cellspacing="0" border="0">
				<tr class="content_blue_side">
					<td class="content_blue_side_right">&nbsp;</td>
				</tr>
				<tr class="content_gray_side">
					<td class="content_gray_side_right">&nbsp;</td>
				</tr>
			</table>		</td>
	    <td class="content_white_side">
			<table cellpadding="0" cellspacing="0" border="0" id="tabletop">
				<tr class="content_blue_side">
					<td class="blue_side_bar">&nbsp;</td>
				</tr>
				<tr class="content_gray_side">
					<td class="gray_side_bar">&nbsp;</td>
				</tr>
			</table>		
		</td>
	</tr>
	<tr class="content_fade">
		<td class="content_white_side">&nbsp;</td>
		<td class="content_bottom_left">
			<table cellpadding="0" cellspacing="0" border="0" id="tablebottom">
				<tr class="content_fade">
					<td class="content_fade_left">&nbsp;</td>
				</tr>
			</table>
		</td>
		<td class="content_bottom_right">
			<table cellpadding="0" cellspacing="0" border="0" id="tablebottom">
				<tr class="content_fade">
					<td class="content_fade_right">&nbsp;</td>
				</tr>
			</table>
		</td>
		<td class="content_white_side">&nbsp;</td>
	</tr>
	<tr class="content_bottom">
		<td class="content_white_side"></td>
		<td></td>
		<td class="content_bottom_line_middle"></td>
		<td></td>
		<td class="content_white_side"></td>
	</tr>
	<tr>
		<td class="content_white_side"></td>
		<td></td>
		<td>
			<table width="794" height="72" cellpadding="0" cellspacing="0">
				<tr>
					<td width="20" rowspan="2"></td>
					<td height="5"></td>
					<td width="20" rowspan="2"></td>
				</tr>
				<tr>
					<td valign="top">
						<?php include("../../includes/footer.inc"); ?>
					</td>
				</tr>
			</table>
		</td>
		<td></td>
		<td class="content_white_side"></td>
	</tr>
</table>
</body>
<!-- InstanceEnd --></html>
