<table width="665" cellpadding="0" border="0" cellspacing="0">
			<tr>
				<td width="660">
					<font class="section_heading">Partnership Programs</font>
									<br />
									<table border="0" cellpadding="1" cellspacing="1">
										<tr>
											<td valign="top">
												<p>Below are the institutions with which Saint Louis Christian College holds partnership programs with. Please click the institution you would like to know more about. The SLCC Registrar can also provide information.</p>
												<ul>
													<li><a href="#umsl" class="headinglink">University of Missouri - St. Louis</a></li>
													<li><a href="#ccc" class="headinglink">Christian College Consortium</a></li>
													<li><a href="#fhsu" class="headinglink">Fort Hays State University</a></li>
													<li><a href="#gc" class="headinglink">Greenville College</a></li>
													<li><a href="#mc" class="headinglink">Milligan College</a></li>
													<li><a href="#pmi" class="headinglink">Pioneer Missions Institute</a></li>
													<li><a href="#stlcc" class="headinglink">St. Louis Community College at Florissant Valley</a></li>
													<li><a href="#gies" class="headinglink">Gateway Internation Education Services</a></li>
												</ul>
											</td>
										</tr>
										<tr>
											<td valign="middle" height="25">
												<img src="../../images/grayline_contentdivider.jpg" width="660" />
											</td>
										</tr>
										<tr>
											<td>
												<font class="section_heading"><a name="umsl">University of Missouri - St. Louis</a></font>
												<br />
												Saint Louis Christian college and the University of Missouri – St. Louis have entered into a cooperative “two-plus-two” program, whereby a student who earns an Associate of Arts in General Studies at SLCC may transfer to UMSL as a Junior. The full range of UMSL’s undergraduate programs is then available to the transferring student, subject to course prerequisites required by specific degree programs plus 6 hours of General Education courses to be taken at UMSL. The university offers many different bachelors’ programs, including Sociology, Accounting, Engineering, Business, and Education. Interested students should work closely with the SLCC registrar for advisement prior to transfer.
											</td>
										</tr>
										<tr>
											<td valign="middle" height="25">
												<img src="../../images/grayline_contentdivider.jpg" width="660" />
											</td>
										</tr>
										<tr>
											<td>
												<font class="section_heading"><a name="ccc">Christian College Consortium</a></font>
												<br />
												Saint Louis Christian College is a partnering school in the consortium of Christian Church Colleges for distance learning. Since the College is a full member of the Consortium, students may enroll in the various courses delivered to individual students by CD-ROM and the Internet. Courses are available every semester and each course has a limited number of students. Special permission to take these distance courses must be obtained through the academic advisor and academic office.
											</td>
										</tr>
										<tr>
											<td valign="middle" height="25">
												<img src="../../images/grayline_contentdivider.jpg" width="660" />
											</td>
										</tr>
										<tr>
											<td>
												<a name="fhsu"><font class="section_heading">Fort Hays State University</font></a>
												<br>
												Saint Louis Christian College and Fort Hays State University, Hays, Kansas, have entered into a co–op plan which enables students to spend their first two years at Saint Louis Christian College receiving the Associate of Arts General Studies degree, gain a biblical education, and spend the last two years at Fort Hays State preparing for work in a secular field, such as education, nursing, agriculture, or pre–law. It is also possible to complete a bachelor program at SLCC and enter graduate work at Fort Hays State.
												<ul>
													<li>More details are available  by contacting the Coordinator of Christian College Cooperatives, Fort Hays State University, Hays, KS 67601.</li>
													<li>Get more information on programs and courses at Fort Hays State University <a href="http://www.fhsu.edu" target="_blank">here</a>. </li>
												</ul>
											</td>
										</tr>
										<tr>
											<td valign="middle" height="25">
												<img src="../../images/grayline_contentdivider.jpg" width="660" />
											</td>
										</tr>
										<tr>
											<td>
												<a name="gc"><font class="section_heading">Greenville College</font></a>
												<br />
												Saint Louis Christian College and Greenville College located in Greenville, Illinois, have entered into a cooperative Two-Plus-Two plan. Students spend the first two years at Saint Louis Christian College earning the Associate of Arts-General Studies degree. Students may then spend the last two years at Greenville College to receive a bachelor’s degree. Over forty–five major programs of interest to students are offered at Greenville College. They range from elementary and secondary education to accounting, business, social work, physical education, chemistry, and modern languages. Greenville College also welcomes SLCC bachelor graduates into its Master of Arts in Teaching degree program.
												<ul>
													<li>Get more information on programs and courses at Greenville College <a href="http://www.greenville.edu" target="_top">here</a>. </li>
												</ul>
											</td>
										</tr>
										<tr>
											<td valign="middle" height="25">
												<img src="../../images/grayline_contentdivider.jpg" width="660" />
											</td>
										</tr>
										<tr>
											<td valign="middle" height="25">
												<img src="../../images/grayline_contentdivider.jpg" width="660" />
											</td>
										</tr>
										<tr>
											<td>
												<a name="mc"><font class="section_heading">Milligan College</font></a>
												<br />
												<em>Master of Education</em>
												<br />
												The Master of Education program at Milligan College in Tennessee is designed for those with a bachelor degree who desire licensure at the elementary level. This program may be completed in one school year and two summers (fifteen months). Saint Louis Christian College graduates are eligible to enter this program and should work carefully with their advisor to ensure the completion of the appropriate coursework.
												<br />
												<ul>
													<li>Get more information on programs and courses at Milligan College <a href="http://www.milligan.edu" target="_blank">here</a>.</li>
												</ul>
											</td>
										</tr>
										<tr>
											<td valign="middle" height="25">
												<img src="../../images/grayline_contentdivider.jpg" width="660" />
											</td>
										</tr>
										<tr>
											<td>
												<a name="pmi"><font class="section_heading">Pioneer Missions Institute</font></a>
												<br />
												Pioneer Bible Translators sponsors this one-week summer program of discovery or readiness for those who want to explore their interest and ability to serve in God's mission in the world. The institute is held in Dallas, Texas, each June. Students may earn college credit for lectures, reading, and tests that are given during the institute. Students may receive credit for the following courses:
												<br/>
												<br />
												<em>PMI I The Discovery Program: Strategy for Missions—Bible Translation</em>
												<br />
												Introduces students to areas of study preparatory to serving effectively on a foreign field, with special attention given to a team approach to Bible translation ministry. The topics include cultural anthropology, team building, phonetics/phonology, linguistics, and language acquisition. 1 Credit.
												<br />
												<br />
												<em>PMI II The Readiness Program: Pre-field Orientation Workshop</em>
												<br />
												Introduces students to dynamics of interpersonal relations for missionaries; development of relations with the sending congregations; meeting educational needs of family; maintenance of physical and emotional health on the field; and development of accounting and reporting method for fiscal accountability. Prerequisite: PMI I or special permission from Pioneer Bible Translators. 1 Credit.
												<ul>
													<li>Get more information on courses at Pioneer Missions Institute <a href="http://www.pioneerbible.org/pmi/index.html" target="_blank">here</a>.</li>
												</ul>
											</td>
										</tr>
										<tr>
											<td valign="middle" height="25">
												<img src="../../images/grayline_contentdivider.jpg" width="660" />
											</td>
										</tr>
										<tr>
											<td>
												<a name="stlcc"><font class="section_heading">St. Louis Community College at Florissant Valley</font></a>
												<br />
												Saint Louis Christian College and St. Louis Community College at Florissant Valley have entered into a partnership program that enables the student to enroll in the Early Care and Education program at Florissant Valley and the Educational Ministry program at Saint Louis Christian College. Upon completion of both programs, the student receives an Associate of Applied Science degree from St. Louis Community College and the Bachelor of Science in Education Ministry degree from Saint Louis Christian College. Students should work carefully with their advisor to ensure the completion of the appropriate coursework. Other programs, such as nursing and deaf education, made available through Florissant Valley can be accomplished concurrently as one studies at SLCC.
												<ul>
													<li>Get more information on programs and courses at St. Louis Community College <a href="http://www.stlcc.edu" target="_blank">here</a>. </li>
												</ul>
											</td>
										</tr>
										<tr>
											<td valign="middle" height="25">
												<img src="../../images/grayline_contentdivider.jpg" width="660" />
											</td>
										</tr>
										<tr>
											<td>
												<a name="gies"><font class="section_heading">Gateway International Educational Services</font></a>
												<br />
												Gateway International Educational Services is directed by Stacy Garner, 1989 graduate of Saint Louis Christian College. This mission provides college and high school internships that earn college credit, opportunity to teach English as a second language abroad, and starts new ministries in unreached areas of the world that have no Christian Churches. By special partnership arrangements, high school juniors and seniors can earn two hours of credit from Saint Louis Christian College at only one-third the cost. Personal experience on the mission field provides the incentive to choose a career in missions. Therefore, SLCC encourages high school students to get a head start on their collegiate education. Here is how it works:
												<ol>
													<li>Register for this partnership missions credit course with GIES.</li>
													<li> Complete the required reading and writing assignments.</li>
													<li>Spend fifteen hours in class time under SLCC’s missions professor during the pre-field orientation session.</li>
													<li>Complete the missions trip with GIES. Students fulfill the requirements for 2 hours of college credit—a required core course in the bachelor and associate degree programs. </li>
												</ol>
												<ul>
													<li>For more information, write: Gateway International Educational Services, c/o Ferguson Christian Church, 303 N. Elizabeth, Ferguson, MO 63135, (314) 521-4850. </li>
												</ul>
											</td>
										</tr>			
									</table>
								</td>
								<td width="5">&nbsp;</td>
							</tr>
						</table>