<span class="style1">PARTNERSHIP PROGRAMS</span>
						<br />
						Students come to college with different goals in mind. You may be thinking "Saint Louis Christian College sounds great but I am not sure that I have been called into full time ministry." We understand. That is why we have developed partnerships with universities throughout the region. You can come to SLCC for two years and get a Bible-centered foundation before transferring to one of our partner schools to fulfill the call that has been put on your life.
						<br />
						<br />