<input type='hidden' name='esh_formmail_return_subject' value="Thank you for your interest in SLCC Athletics!" />
		<form name="frmFormMail" action="index.php" method='post' enctype='multipart/form-data'>
		<input type='hidden' name='formmail_submit' value='Y'>
		<input type='hidden' name='esh_formmail_subject' value="athletic questionnaire submittal">
		<input type='hidden' name='esh_formmail_recipient' value="admissions@slcconline.edu, athletics@slcconline.edu">
		<input type='hidden' name='esh_formmail_cc' value="">
		<input type='hidden' name='esh_formmail_bcc' value="">
		<input type='hidden' name='esh_formmail_return_msg' value="We have received your request and you will receive more information on the area of your interest ASAP.  Thank you!
		
		-Saint Louis Christian College Athletics">
		<input type='hidden' name='esh_formmail_mail_and_file' value="">
		<input type='hidden' name='esh_formmail_charset' value="">
                          <em>To receive more information about SLCC Athletics, please fill out this 5-minute form so that we may learn a little more about you.</em>
						  <br />
							<table width="500" border='0' cellpadding='4' cellspacing='0'>
								<tr>
									<td colspan="3"><img src="../../../images/grayline_contentdivider.jpg" width="500" border="0" /></td>
								</tr>
								<tr>
									<td height="3" colspan="3" align='right' valign='top'>
										<div align="left"><h2><strong>Personal Information</strong></h2>
										</div>									</td>
								</tr>
								<tr>
									<td align='right' valign='top'><div align="right">First &amp; Last Name:</div></td>
									<td width="8" valign='top' aligh='right'><font color='#ff0000'>*</font></td>
									<td width="225" class="form_text"><input name="Full_Name" type="text" id="Full_Name"></td>
								</tr>
								<tr>
									<td align='right' valign='top'><div align="right">Address:</div></td>
									<td width="8" valign='top' aligh='right'><font color='#ff0000'>*</font> </td>
									<td class="form_text"><input type="text" name="Address" /></td>
								</tr>
								<tr>
									<td align='right' valign='top'><div align="right">Address (Line 2):</div></td>
									<td width="8" valign='top' aligh='right'></td>
									<td class="form_text"><input type="text" name="Address_(Line_2)" ></td>
								</tr>
								<tr>
									<td align='right' valign='top'><div align="right" class="style7">City: </div></td>
									<td width='8' valign='top'  aligh='right'><font size='2' color='#ff0000'>*</font> </td>
									<td class="form_text"><input type="text" name="City"></td>
								</tr>
								<tr>
									<td align='right' valign='top'><div align="right">State: </div></td>
									<td width="8" valign='top' aligh='right'><font color='#ff0000'>*</font> </td>
									<td class="form_text">
										<select name="State" id="State">
											<OPTION VALUE=All> All</OPTION>
											<OPTION VALUE=AL> Alabama</OPTION>
											<OPTION VALUE=AK> Alaska</OPTION>
											<OPTION VALUE=AZ> Arizona</OPTION>
											<OPTION VALUE=AR> Arkansas</OPTION>
											<OPTION VALUE=CA> California</OPTION>
											<OPTION VALUE=CO> Colorado</OPTION>
											<OPTION VALUE=CT> Connecticut</OPTION>
											<OPTION VALUE=DE> Delaware</OPTION>
											<OPTION VALUE=FL> Florida</OPTION>
											<OPTION VALUE=GA> Georgia</OPTION>
											<OPTION VALUE=HI> Hawaii</OPTION>
											<OPTION VALUE=ID> Idaho</OPTION>
											<OPTION VALUE=IN> Indiana</OPTION>
											<OPTION VALUE=IL> Illinois</OPTION>
											<OPTION VALUE=IA> Iowa</OPTION>
											<OPTION VALUE=KS> Kansas</OPTION>
											<OPTION VALUE=KY> Kentucky</OPTION>
											<OPTION VALUE=LA> Louisiana</OPTION>
											<OPTION VALUE=ME> Maine</OPTION>
											<OPTION VALUE=MD> Maryland</OPTION>
											<OPTION VALUE=MA> Massachussets</OPTION>
											<OPTION VALUE=MI> Michigan</OPTION>
											<OPTION VALUE=MN> Minnesota</OPTION>
											<OPTION VALUE=MS> Mississippi</OPTION>
											<OPTION VALUE=MO> Missouri</OPTION>
											<OPTION VALUE=MT> Montana</OPTION>
											<OPTION VALUE=NE> Nebraska</OPTION>
											<OPTION VALUE=NV> Nevada</OPTION>
											<OPTION VALUE=NJ> New Jersey</OPTION>
											<OPTION VALUE=NY> New York</OPTION>
											<OPTION VALUE=NH> New Hampshire</OPTION>
											<OPTION VALUE=NM> New Mexico</OPTION>
											<OPTION VALUE=NC> North Carolina</OPTION>
											<OPTION VALUE=ND> North Dakota</OPTION>
											<OPTION VALUE=OH> Ohio</OPTION>
											<OPTION VALUE=OK> Oklahoma</OPTION>
											<OPTION VALUE=OR> Oregon</OPTION>
											<OPTION VALUE=PA> Pennsylvania</OPTION>
											<OPTION VALUE=RI> Rhode Island</OPTION>
											<OPTION VALUE=SC> South Carolina</OPTION>
											<OPTION VALUE=SD> South Dakota</OPTION>
											<OPTION VALUE=TN> Tennessee</OPTION>
											<OPTION VALUE=TX> Texas</OPTION>
											<OPTION VALUE=UT> Utah</OPTION>
											<OPTION VALUE=VA> Virginia</OPTION>
											<OPTION VALUE=VT> Vermont</OPTION>
											<OPTION VALUE=WA> Washington</OPTION>
											<OPTION VALUE=WV> West Virginia</OPTION>
											<OPTION VALUE=WI> Wisconsin</OPTION>
											<OPTION VALUE=WY> Wyoming</OPTION>
										</SELECT>									</td>
								</tr>
								<tr>
									<td align='right' valign='top'><div align="right">Country:</div></td>
									<td valign='top' aligh='right'>&nbsp;</td>
									<td class="form_text"><input name="Country" type="text" id="Country" size="15"></td>
								</tr>
								<tr>
									<td align='right' valign='top'><div align="right">ZIP:</div></td>
									<td width='8' valign='top'  aligh='right'>&nbsp;</td>
									<td class="form_text"><input name="ZIP" type="text" size="5" maxlength="10"></td>
								</tr>
								<tr>
									<td align='right' valign='top'><div align="right">Phone Number:</div></td>
									<td valign='top'  aligh='right'>&nbsp;</td>
									<td class="form_text"><input name="Phone" type="text" id="Phone" size="12"></td>
								</tr>
								<tr>
									<td align='right' valign='top'><div align="right">E-mail Address: </div></td>
									<td width='8' valign='top'  aligh='right'><font color='#ff0000'>*</font> </td>
									<td class="form_text"><input type="sender's email" name="E-mail_Address"></td>
								</tr>
								<tr>
									<td align='right' valign='top'><div align="right">Birthdate (ex. 00-00-0000): </div></td>
									<td width='8' valign='top'  aligh='right'><font color='#ff0000'>*</font> </td>
									<td class="form_text"><input name="Birthdate" type="text" size="10" maxlength="10"></td>
								</tr>
								<tr>
									<td align='right' valign='top'><div align="right">Church you currently attend: </div></td>
									<td valign='top'  aligh='right'>&nbsp;</td>
									<td class="form_text"><input name="Church" type="text" id="Church"></td>
								</tr>
								<tr>
									<td align='right' valign='top'>Parents' Name(s): </td>
									<td valign='top' aligh='right'>&nbsp;</td>
									<td class="form_text"><input name="Parents" type="text" id="Parents"></td>
								</tr>
								<tr>
									<td colspan="3"><img src="../../../images/grayline_contentdivider.jpg" width="500" border="0" /></td>
								</tr>
								<tr>
									<td height="3" colspan="3" align='right' valign='top'><div align="left"><h2><strong>Academic Information</strong></h2></div></td>
								</tr>
								<tr>
									<td colspan="3" align='right' valign='top'><div align="left"><strong>High School Information: </strong></div></td>
								</tr>
								<tr>
									<td align='right' valign='top'>High School Attended:</td>
									<td valign='top'  aligh='right'><font color='#ff0000'>*</font></td>
									<td valign="top" class="form_text"><input name="highschool" type="text" id="highschool"></td>
								</tr>
								<tr>
									<td align='right' valign='top'>GPA:</td>
									<td valign='top'  aligh='right'><font color='#ff0000'>*</font></td>
									<td class="form_text"><input name="gpa" type="text" id="gpa" size="4"></td>
								</tr>
								<tr>
									<td align='right' valign='top'><div align="right" class="style7">Year of High School Graduation: </div></td>
									<td valign='top' aligh='right'><font color='#ff0000'>*</font> </td>
									<td class="form_text"><input name="hs_graduation" type="text" id="hs_graduation"  size="4" maxlength="8"></td>
								</tr>
								<tr>
									<td colspan="3" align='right' valign='top'><div align="left"><strong>Junior College Information (If Applicable):</strong></div></td>
								</tr>
								<tr>
									<td align='right' valign='top'>Junior College Attended?</td>
									<td valign='top' aligh='right'>&nbsp;</td>
									<td class="form_text"><input name="juniorcollege" type="text" id="juniorcollege"></td>
								</tr>
								<tr>
									<td colspan="3" align='right' valign='top'><div align="left"><strong>Other College Information (If Applicable):</strong></div></td>
								</tr>
								<tr>
									<td align='right' valign='top'>Other College Attended?</td>
									<td valign='top'  aligh='right'>&nbsp;</td>
									<td class="form_text"><input name="othercollege" type="text" id="othercollege"></td>
								</tr>
								<tr>
									<td colspan="3"><img src="../../../images/grayline_contentdivider.jpg" width="500" border="0" /></td>
								</tr>
								<tr>
									<td height="3" colspan="3" valign='top'><div align="left"><h2><strong>Athletic Information</strong></h2></div></td>
								</tr>
								<tr>
									<td align='right' valign='top'>
										<p>Sport of Interest: </p>
										<p align="left">To select more than one sport please hold down the ctrl key and click the sports desired.</p></td>
										<td valign='top'  aligh='right'>&nbsp;</td>
										<td valign="top" class="form_text">
											<select name="sport_interest" size="6" multiple id="sport_interest">
											  <option value="baseball">baseball</option>
											  <option value="m_basketball">men's basketball</option>
											  <option value="w_basketball">women's basketball</option>
											  <option value="soccer">men's soccer</option>
											  <option value="volleyball">women's volleyball</option>
											  <option value="womans_cross_country">women's cross country</option>
											</select>										</td>
								</tr>
								<tr>
									<td align='right' valign='top'>
										<p>Positions Played:<br></p>
										<p align="left">You may list multiple positions and multiple sports. </p>									</td>
									<td valign='top'  aligh='right'>&nbsp;</td>
									<td class="form_text"><textarea name="positions_played" id="positions_played"></textarea></td>
								</tr>
								<tr>
									<td align='right' valign='top'>Height:</td>
									<td valign='top'  aligh='right'>&nbsp;</td>
									<td class="form_text"><input name="height" type="text" id="height" size="6"></td>
								</tr>
								<tr>
									<td align='right' valign='top'>Weight:</td>
									<td valign='top'  aligh='right'>&nbsp;</td>
									<td class="form_text"><input name="weight" type="text" id="weight" size="6"></td>
								</tr>
								<tr>
									<td align='right' valign='top'>Coach's Name (High School or Other):</td>
									<td valign='top'  aligh='right'>&nbsp;</td>
									<td class="form_text"><input name="coach_name" type="text" id="coach_name"></td>
								</tr>
								<tr>
									<td align='right' valign='top'>Phone Number:</td>
									<td valign='top'  aligh='right'>&nbsp;</td>
									<td class="form_text"><input name="coach_phone_number" type="text" id="coach_phone_number" size="12"></td>
								</tr>
								<tr>
									<td align='right' valign='top'>Number of Years Played:</td>
									<td valign='top'  aligh='right'>&nbsp;</td>
									<td class="form_text"><input name="years_played" type="text" id="years_played" size="2"></td>
								</tr>
								<tr>
									<td align='right' valign='top'>Comments/Additional Information:</td>
									<td valign='top'  aligh='right'>&nbsp;</td>
									<td class="form_text"><textarea name="comments" id="comments"></textarea></td>
								</tr>
								<tr>
									<td colspan="3"><img src="../../../images/grayline_contentdivider.jpg" width="500" border="0" /></td>
								</tr>
								<tr>
									<td height="3" colspan=3 align='center'>
										<input type='submit' value='Submit'>&nbsp;&nbsp;<input type='button' value='Cancel' onclick="location.href='/';">
									</td>
								</tr>
							</table>
            </form>