<table border="0" cellpadding="0" cellspacing="0" width="533">
				<tr>
					<td width="528">
						<font class="section_heading">CAMPUS LIFE</font>
						<br /><br />
						Some of the most important lessons you will learn at Saint Louis Christian College will happen outside of the classroom. From dorm life to spiritual development to clubs and activities, they all play a crucial part in the college experience. There are so many ways to get involved.
				  </td>
				  <td width="5">&nbsp;</td>
				</tr>
				<tr>
					<td height="25" colspan="2"><img src="../../../images/grayline_contentdivider.jpg" width="533" /></td>
				</tr>
				<tr>
				  <td>
						<span class="style1">Residence Halls</span>
						<br />
						Living on campus is one of the best ways to build lasting memories and make lifelong friendships. Whether it's a movie marathon, late night pizza runs or talking until the wee hours of the morning you are cultivating friendships that will always be a part of your life.
						<br />
						<ul>
							<li><a href="../campus_life/residence_halls/">Bethany Hall</a></li>
							<li><a href="../campus_life/residence_halls/">Bethesda Hall</a></li>
							<li><a href="../campus_life/residence_halls/">Berea Hall</a></li>
							<li><a href="../campus_life/residence_halls/">On-Campus Apartments</a></li>
						</td>
					<td width="5">&nbsp;</td>
				</tr>
				<tr>
					<td height="25" colspan="2"><img src="../../../images/grayline_contentdivider.jpg" width="533" /></td>
				</tr>
				<tr>
					<td>
						<span class="style1">Spiritual Development</span>
						<br />
						The faculty and staff of Saint Louis Christian College is devoted to the spiritual development of our students. Students are encouraged to strengthen their relationship with Christ through regular worship services and daily private devotions. There are many opportunities for worship and ministry as a number of churches are within easy driving distance. Chapel services, residence hall devotions, field participation and mission trips are also encouraged.
					</td>
					<td width="5">&nbsp;</td>
				</tr>
				<tr>
					<td height="25" colspan="2"><img src="../../../images/grayline_contentdivider.jpg" width="533" /></td>
				</tr>
				<tr>
					<td>
						<span class="style1">Student Leadership</span>
						<br />
						The emotional growth of students can be enhanced through leadership roles among their peers. The College offers a number of ways to take a leadership role within the student community:
						<br />
						<br />
						<b>Student Government Association (SGA)</b> - Student Government acts as a liaison between the student body and the administration. SGA duties include regular meetings, planning activities and assisting with new student orientation. Officers are elected by each class. Upper-class representatives are selected in the spring prior to their term, while freshman representatives are selected early in the fall semester.
						<br />
						<br />
						<b>World Christians United (WCU)</b> - The mission of WCU is to build intercultural awareness and create a vision for Christian evangelistic services. This group accomplishes its goals through regular meetings, prayer times and service projects. WCU may also appoint a representative to the SGA.
						<br />
						<br />
						<b>Class Officers</b> - Students of each class elect their president, vice president, secretary/treasurer, and a faculty sponsor.
						<br />
					</td>
					<td width="5">&nbsp;</td>
				</tr>
				<tr>
					<td height="25" colspan="2"><img src="../../../images/grayline_contentdivider.jpg" width="533" /></td>
				</tr>
				<tr>
					<td>
						<span class="style1">Student Activities</span>
						<br />
						The goal of Saint Louis Christian College is to aid students to develop as well-rounded Christians. The College encourages and provides activities allowing students to explore another dimension of interpersonal growth.
						<br />
						<br />
						<b>Athletics</b> - Saint Louis Christian College is a member of the National Christian College Athletic Association (NCCAA). The Soldiers compete against mostly NAIA and other NCCAA colleges in baseball, soccer, basketball and volleyball.
						<br />
						<br />
						<b>Travel Teams</b> - The Admissions Department selects students to represent SLCC during the summer at various camps, conferences and churches. Travel teams are chosen in the spring.
						<br />
						<br />
						<b>Music Groups</b> - SLCC has an ensemble group that performs at various churches and in chapel services throughout the year. Auditions are held at the beginning of each semester.
						<br />
						<br />
						<b>Musical/Drama Programs</b> - SLCC supports musical/drama outreach programs that provide a cultural development opportunity every other spring. Students with musical and dramatic abilities and interests are encouraged to audition.
						<br />	
					</td>
					<td width="5">&nbsp;</td>
				</tr>
			</table>