<table cellpadding="0" cellspacing="0" border="0" width="533">
				<tr>
					<td background="../../../images/admissions/city_life/sky_line.jpg" width="528">
						<font class="section_heading">Saint Louis-City Life</font>
						<br />
						<br />
						The City of St. Louis, founded in 1764, is commonly known as the "Gateway to the West." Established by French fur traders and named for Louis IX, former king of France, St. Louis has become one of the largest and most popular cities in the Mid-West.
						<br />
						<br />
						The Gateway Arch, built in 1965, is the trademark of the city, standing 630 feet tall. It is the tallest national monument in the country and the fourth most-visited tourist attraction in the world.
						<br />
						<br />
						St. Louis offers great attractions, such as Forest Park, which is home to the St. Louis Art Museum, the Missouri History Museum, the Science Center, the St. Louis Zoo and the Muny. Forest Park is the seventh largest urban park in the United States at 1,371 acres, 500 acres larger than New York City's famed Central Park.
						<br />
						<br />
						Another famous attraction is St. Louis' Union Station which at its peak saw more than 100,000 people pass through in a single day. Now Union Station functions as a mall containing more than 100 shops and restaurants.
						<br />
						<br />
						One of the most popular locations in St. Louis is the U. City Loop, which contains more than 120 boutiques, specialty shops, restaurants, galleries & live entertainment over a six-block area. It is a popular spot for college students due to the great range of prices at the restaurants and boutiques.
						<br />
						<br />
						Much of downtown St. Louis has been or is currently being renovated and remodeled. New hotels, restaurants, theatres, parks were built and many other building projects have been set into motion in order to spark growth and revitalize downtown St. Louis.
						<br />
					</td>
					<td width="5">&nbsp;</td>
				</tr>
				<tr>
					<td height="25" colspan="2"><img src="../../../images/grayline_contentdivider.jpg" width="530" /></td>
				</tr>
				<tr>
					<td>
						<font class="section_heading">Saint Louis-Sports</font>
						<br />
						<br />
						St. Louis has enjoyed a rich tradition of professional sports. It is home to the St. Louis Cardinals, Rams, and Blues.
						<br />
						<br />
						The Cardinals play their home games at Busch Stadium which was built in 2006. The Cardinals started their inaugural season in their new stadium as World Series Champions.
						<br />
						<br />
						The Rams are St. Louis' second NFL team and have appeared in two Super Bowls since coming to St. Louis, winning Super Bowl XXXIV in 2000 under head coach Dick Vermeil.
						<br />
						<br />
						St. Louis was awarded an NHL franchise in 1967. Named the St. Louis Blues, they play their home games at the Scotttrade Center in downtown St. Louis.
						<br />
						<br />
					</td>
					<td width="5">&nbsp;</td>
				</tr>
			</table>