                <table border="0" cellpadding="2" cellspacing="1" width="190">
					<tr>
                    	<td><font class="section_heading">Class Schedules</font> </td>
                  	</tr>
                  	<tr>
                    	<td bgcolor="#003974">&nbsp;</td>
                  	</tr>
                  	<tr>
                    	<td>
							<a href="../../../academics/course_schedules/pdf/AcademicCalendar2013-2014.pdf" target="_blank">2013-2014 Academic Calendar</a> <img src="../../../images/PDF_icon.gif" /> <br />
                        	<a href="../../../academics/course_schedules/pdf/AimFall2013.pdf" target="_blank">Fall 2013 AIM Class Schedule</a> <img src="../../../images/PDF_icon.gif" /> <br />
							<a href="../../../academics/course_schedules/pdf/DayFall2013.pdf" target="_blank">Fall 2013 DAY Class Schedule</a> <img src="../../../images/PDF_icon.gif" /><br />
							<a href="../../../academics/syllabi" target="_blank">Course Syllabi</a>
						</td>
                  	</tr>
                 	<tr>
                    	<td bgcolor="#003974">&nbsp;</td>
                  	</tr>
              	</table>