<span class="style1">FINANCIAL AID-Costs and Fees:</span>
			<br />
			<br />
				<table width="520" border="0" cellspacing="1" cellpadding="1">
					<tr>
						<td colspan="3"><strong>Costs and Fees for Day Students:</strong></td>
					</tr>
					<tr>
						<td colspan="2">Full-Time Day Residential Students:</td>
						<td width="260">Per Semester</td>
					</tr>
					<tr>
						<td width="50">&nbsp;</td>
						<td width="210">Tuition</td>
						<td>$4,107.50 (15.5 hours)</td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>Room/Board</td>
						<td>$2,000</td>
					</tr>
					<!--<tr>
						<td>&nbsp;</td>
						<td>Fees</td>
						<td>$650</td>
					</tr>-->
					<tr>
						<td colspan="2">&nbsp;</td>
						<td>&nbsp;</td>
					</tr>
					<tr>
						<td colspan="3">Full-Time Day Commuter Students:</td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>Tuition</td>
						<td>$4,107.50 (15.5 hours)</td>
					</tr>
					<!--<tr>
						<td>&nbsp;</td>
						<td>Fees</td>
						<td>$650</td>
					</tr>-->
					<tr>
						<td colspan="2">&nbsp;</td>
						<td>&nbsp;</td>
					</tr>
					<tr>
						<td colspan="3">Part-Time Day Students (less than 12 credit hours):</td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>Tuition</td>
						<td>$265 per credit hour</td>
					</tr>
					<!--<tr>
						<td>&nbsp;</td>
						<td>Fees</td>
						<td>$650 </td>
					</tr>-->
				</table>
				<table width="533" cellpadding="0" cellspacing="0" border="0">
					<tr>
						<td height="25"><img src="../../../../images/grayline_contentdivider.jpg" width="533"/></td>
					</tr>
				</table>
				<table width="520" border="0" cellspacing="1" cellpadding="1">
					
					<tr>
						<td colspan="3"><strong>Costs and Fees for AIM Students</strong></td>
					</tr>
					<tr>
						<td colspan="3">Full-Time AIM Residential Students</td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>Tuition</td>
						<td>$3,312.50 (12.5 hours)</td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>Room/Board</td>
						<td>$3,000</td>
					</tr>
					<!--<tr>
						<td>&nbsp;</td>
						<td>Fees</td>
						<td>$650</td>
					</tr>-->
					<tr>
						<td colspan="2">&nbsp;</td>
						<td>&nbsp;</td>
					</tr>
					<tr>
						<td colspan="3">Full-Time AIM Commuter Students:</td>
					</tr>
					<tr>
						<td width="50">&nbsp;</td>
						<td width="210">Tuition</td>
						<td>$3,312.50 (12.5 hours)</td>
					</tr>
					<!--<tr>
						<td>&nbsp;</td>
						<td>Fees</td>
						<td>$650</td>
					</tr>-->
					<tr>
						<td colspan="2">&nbsp;</td>
						<td>&nbsp;</td>
					</tr>
					<tr>
						<td colspan="3">Part-Time AIM Students (less than 12 credit hours):</td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>Tuition</td>
						<td>$265 per credit hour</td>
					</tr>
					<!--<tr>
						<td>&nbsp;</td>
						<td>Fees</td>
						<td>$500</td>
					</tr>-->
				</table>
				
				<table width="533" cellpadding="0" cellspacing="0" border="0">
					<tr>
						<td height="25"><img src="../../../../images/grayline_contentdivider.jpg" width="533"/></td>
					</tr>
				</table>

			<!--<strong>Reservation and Orientation Fee for First-Year Students</strong>
			<br />
			All first-year students, including transfer students, must pay a $250 non-refundable reservation and orientation fee. This fee reserves your space and covers the cost of orientation weekend. This fee is due upon acceptance to SLCC to verify your commitment to attend. 
			<br />
			<br />-->
			<strong>Other Costs for Residential Students <em>(Including First-Year Students)</em></strong>
			<br />
			All students living on-campus are required to pay all room and board costs at time of registration. For day students, a double-occupancy room costs $2,000 per semester, which includes housing during the school semester and 13 meals per week while school is in session. For AIM students, a double-occupancy room costs $3,000 per semester, which includes year-round housing and 13 meals a week while school is in session. Apartment housing for non-traditional students is available starting at $2,370. Apartment housing price does not include meals; however, they are available for purchase at an additional cost.<br /><br />