<table border="0" cellpadding="0" cellspacing="0" width="533">
				<tr>
					<td width="528">
						<span class="style1">FINANCIAL AID</span>
						<br />
						<ul>
							<li><a href="../financial_aid/costs_and_fees/">Costs and Fees</a></li>
							<li><a href="../financial_aid/financial_aid_and_scholarships/">Financial Aid/Scholarships</a></li>
							<li><a href="../../../academics/financial_aid/NetPrice/index.php">NetPrice Calculator</a></li>
							<li><a href="../financial_aid/loan_application/">Loan Application</a></li>
							<li><a href="http://www.fafsa.ed.gov/" target="_blank">FAFSA- Free Application for Federal Student Aid</a></li>
						</ul>
				  </td>
				  <td width="5">&nbsp;</td>
				</tr>
			</table>