<table width="533" border="0" cellpadding="0" cellspacing="0">
			<tr>
				<td>
					<span class="style1">Financial Aid/Scholarships</span>
					<br />
					<br />
					<em>To be considered for any type of financial aid, students must first submit the Free Application for Federal Student Aid (FAFSA) and a Saint Louis Christian College Financial Aid Application  each year.</em>
					<br />
					<br />
						<table width="528" cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td height="25"><img src="../../../../images/grayline_contentdivider.jpg" width="528"/></td>
							</tr>
						</table>
						<span class="style1">Federal Programs</span>
						<br />
						<em>To qualify for any federal programs, students must demonstrate a need by submitting a Free Application for Federal Student Aid (FAFSA). A number of federal programs are available:</em>
						<br />
						<br />
						<strong>Pell Grant</strong> - Maximum Pell Grant for 2013-2014 is $5,645 per year. Minimum amount is $400 per year.
						<br />
						<br />
						<strong>Supplemental Educational Opportunity Grant (SEOG)</strong> - This grant is for students demonstrating exceptional need. Average award is $400. Priority deadline for consideration is June 15 for students beginning in the fall, and November 15 for students beginning in the spring.
						<br />
						<br />
						<strong>Federal Work-Study Program (FWS)</strong> - FWS is a federally funded program which enables students to work part-time on campus. Pay starts at minimum wage. Jobs are limited and preference is given to upperclassmen.
						<br />
						<br />
						<strong>Stafford Loan Program</strong> - This is a government-sponsored loan for students enrolled at least half time during the semester. Repayment begins six months after the student terminates college enrollment or is no longer at least half time. Maximum amount for freshmen is $3,500; sophomores, $4,500; juniors and seniors, $5,500. Independent students may be able to borrow between $4,000 and $5,000 a year in unsubsidized loans, depending upon need and grade classification.
						<br />
						<br />
						<strong>Parent Loans for Undergraduate Students (PLUS)</strong> - Parents of students may borrow toward their dependents' education. The PLUS program enables parents to borrow an amount equal to the cost of education minus financial aid. Payment of interest and principal begins sixty (60) days after the final disbursement in the year. In addition to base grade level amounts, independent freshman and sophomore students may be able to borrow up to $4,000 and independent junior and senior students may be able to borrow up to $5,000 a year in unsubsidized loans, depending upon need.
						<br />
						<table width="528" cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td height="25"><img src="../../../../images/grayline_contentdivider.jpg" width="528"/></td>
							</tr>
						</table>
						<span class="style1">Alternative Education Loans</span>
						<br />
						Sometimes students need additional loan funds beyond what they can borrow through the Stafford Loan but their parents are unwilling to apply for a PLUS loan. In that event, an alternative (non-federal) loan, which is in the student's name, might be the answer.
						<br />
						<br />
						Although the interest rates on these loans are generally higher than the Stafford or PLUS loans, there may be other benefits, such as longer repayment periods, no up-front fees, deferred repayment while in school, etc.
						<br />
						<br />
						There are some requirements, however. The student must either pass a credit check or have a co-signer who is able to pass the credit check.
						<br />
						<table width="528" cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td height="25"><img src="../../../../images/grayline_contentdivider.jpg" width="528"/></td>
							</tr>
						</table>
						<span class="style1">Veteran Benefits</span>
						<br />
						Financial assistance may be available to veterans of the armed forces. Students should apply at their nearest Veterans Administration Office. Saint Louis Christian College is approved for veterans' educational benefits.
						<br />
						<table width="528" cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td height="25"><img src="../../../../images/grayline_contentdivider.jpg" width="528"/></td>
							</tr>
						</table>
						<span class="style1">Vocational Rehabilitation</span>
						<br />
						Students with physical disabilities that constitute substantial vocational handicaps may be eligible for grants. These funds are administrated through area offices of the Division of Vocational Rehabilitation.
						<br />
						<table width="528" cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td height="25"><img src="../../../../images/grayline_contentdivider.jpg" width="528"/></td>
							</tr>
						</table>
					</td>
					<td width="5">&nbsp;</td>
				</tr>
			</table>