<span class="style1">Ministry Advancement Program</span>
			<br />
			<br />
			As part of SLCC's academic programs to prepare students for a lifetime of ministry, students are enrolled in the Ministry Advancement Program (MAP) every semester they are in attendance at the college. The MAP program is graded on a pass/fail basis and will appear on student transcripts.<strong>Participation in the Ministry Advancement Program is required for graduation.</strong>
			<br />
			<br />
			The Ministry Advancement Program consists of three separate areas of development in the lives of students. They are: Character Development, Community Development, and Church Development.  Students are involved in activities in each of these developmental areas every semester.
			<br />
			<br />
			<strong>Character Development:</strong> Each student will grow in his or her personal maturity in Christ through chapel, discipleship groups, on-campus work positions and self-discovery exercises. The personal interaction provided in discipleship groups and the campus work program is a hallmark of the MAP program, helping us build personal relationships with our students.  This relational component enables us to design individualized learning experiences which accommodate and enhance each student's personal gift mix, personality and spiritual formation needs.
			<br />
			<br />
			<strong>Community Development:</strong> Each student will develop a growing attitude of servanthood in the college and larger community. This will include on-campus service, community service and involvement in various campus student organizations (athletics, student government, etc.). The program also includes experience in a variety of community settings (urban, suburban, and rural).
			<br />
			<br />
			<strong>Church Development:</strong> Each student will grow in his or her ability to lead in the church. This will include ministry in the church and/or para-church organizations and may also include college outreach teams (music groups, camp teams, supply preaching, etc.).
			<br />
			<br />
			With the underlying goal of making the MAP experience highly personalized, the exact nature of each student's involvements will be determined in consultation with the MAP Coordinator on the basis of individual goals, interests, and needs.  Within the framework of the three areas of development, students may design their own MAP projects and submit them for approval to be used towards MAP points.  The goal of incorporating MAP projects into the point system is to allow opportunity for self-directed learning and add some flexibility for students to obtain points in a way that is personally meaningful.
			<br />
			<br />
			Students are evaluated on the extent to which they have accrued the appropriate number of points in each of the developmental areas, as well as on meeting attendance requirements for participation in all aspects of the program (e.g., chapel, small groups, Lab Week, and Leadership Intensive Week).  Because the faculty and administration take MAP participation very seriously, the penalties for failing MAP are rather severe (possible penalties include suspension or postponed graduation). We have designed the Ministry Advancement Program to be one of the key pieces for equipping our students for service, and further believe it is an indicator of a student's servant attitude.
			<br />
			<br />The Ministry Advancement Program is based on a service learning model. By serving on campus, in churches, and in community organizations students gain practical ministry experience.  At some phases of the program, the service commitment can average five or more hours per week. It is important to keep this in mind when planning course schedules and other time commitments. This service will be a vital learning link between the classroom and students' ultimate ministry goals. Upon graduation, students will have experienced a variety of guided and self-directed ministry activities and will be well-equipped for the ministries to which they are called.  More specific information about MAP is detailed in the MAP Manual, which is also available from the MAP Office.  Please, also feel free to contact the MAP Coordinator, Barbara Veech, for additional information on this vital component of Saint Louis Christian College's academic program.
			<br /><br />