<table width="533" border="0" cellpadding="0" cellspacing="0">
			<tr>
				<td colspan="2"><span class="style1">Residence Halls</span><br /></td>
			</tr>
			<tr>
				<td width="300">
					<strong><a name="bethany">BETHANY HALL</a></strong>
					<br />
					Women&rsquo;s Dormitory
					<br />
					Resident Director- <u>Cindy Bingmon</u>
					<br />
					Resident Assistant- <u>Teresa Sams</u>
					<br />
					<br />
					Bethany Hall is a female residence hall that is fully air  conditioned and has the capacity to hold 40 students. Each room holds 2 girls  with a community bathroom on each floor. There is a fully equipped kitchen in Bethany and each room  comes furnished with a bed, dresser and desk for each student. All rooms are  equipped with internet hook-ups.				</td>
				<td width="233">&nbsp;</td>
			</tr>
			<tr>
				<td height="25" colspan="2"><img src="../../../../images/grayline_contentdivider.jpg" width="533"/></td>
			</tr>
			<tr>
				<td>
					<strong><a name="bethesda">BETHESDA HALL</a></strong>
					<br />
					Women&rsquo;s Dormitory
					<br />
					Resident Director- <u>Cindy Bingmon</u>
					<br />
					Resident Assistant- <u>Laura Farrar</u>
					<br />
					<br />
					Bethesda Hall is a female residence hall that is fully air  conditioned and has the capacity to hold 40 students. Each room holds 2 girls  with a community bathroom on each floor. There is a fully equipped kitchen and  a newly remodeled lounge in Bethany.  Each room comes furnished with a bed, dresser and desk for each student. All  rooms are equipped with internet hook-ups.
				</td>
				<td width="233">&nbsp;</td>
			</tr>
			<tr>
				<td height="25" colspan="2"><img src="../../../../images/grayline_contentdivider.jpg" width="533"/></td>
			</tr>
			<tr>
				<td>
					<strong><a name="berea">BEREA HALL</a></strong>
					<br />
					Men&rsquo;s Dormitory
					<br />
					Resident Director- <u>James McFarland</u>
					<br />
					Resident Assistant- <u>Justin Miller</u>, <u>Brock Howard</u> and <u>Matt Farrar</u>
					<br />
					<br />
					Berea Hall is a male residence hall that is fully air  conditioned and has the capacity to hold 90 students. Each room holds 2 men  with a community bathroom on each floor. There is a fully equipped kitchen and  each room comes furnished with a bed, dresser and desk for each student. All  rooms are equipped with internet hook-ups.
				</td>
				<td width="233">&nbsp;</td>
			</tr>
			<tr>
				<td height="25" colspan="2"><img src="../../../../images/grayline_contentdivider.jpg" width="533"/></td>
			</tr>
			<tr>
				<td>
					<strong><a name="#on_campus">ON CAMPUS APARTMENTS</a></strong>
					<br />
					Married and Single Parents with Children
					<br />
					<br />
					Our on campus apartments are offered to married students and single students with children. Each unit holds between 2 and 4 persons. Each unit is air conditioned and has a fully equipped kitchen. We also provide a bed, dresser  and desk for each student in the apartment.
				</td>
				<td width="233">&nbsp;</td>
			</tr>
		</table>