<span class="style1">Visit SLCC</span>
		<br />
		We understand that the college search is tough. Which college offers the best education? Which college has the program I am looking for? Which college is the perfect fit for me? You will never know until you see a college up close and personal. That is why we would like to invite you to visit Saint Louis Christian College. At SLCC, you can worship with our students in a chapel service, learn with our students by attending a class, meet our students as you take a tour of our campus and even live with our students by staying the night in our dorms. Please contact our admissions office for more information on visiting our campus.
		<br />
		<br />
		<strong>Call the Office of Admissions today! 314-837-6777 ext. 8110 or 1-800-887-SLCC(7522)</strong>