<table width="754" height="67">
	<tr>
		<td width="25%" align="left" valign="top">
			<a href="/contact/">Contact SLCC</a>
			<br />
			<a href="/site_map/">Site Map</a></td>
		<td width="50%" align="center" valign="top">
			1360 Grandview Dr. Florissant, MO. 63033 | Phone: 314-837-6777
			<br />
			&copy; 2008 Saint Louis Christian College
			<br />
			<a href="javascript:linkTo_UnCryptMailto('nbjmup;xfcnbtufsAtmddpomjof/fev');">Contact the Webmaster</a></td>
		<td width="25%" align="right" valign="top"><div align="right"><a href="/portal/" border="0"><img src="/images/soldier.gif" border="0"/></a></div>
		<?php include('analyticstracking.php'); ?></td>
	</tr>
</table>