<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
    <td bgcolor="#003974"><div align="center">
	<table border="0" cellpadding="0" cellspacing="0" width="860">
  <tr>
  <td><img src="/images/spacer.gif" width="860" height="1" border="0" alt=""></td>
  </tr>
  <td rowspan="3"><a href="/index.php"><img src="/images/header.jpg" width="860" height="110" border="0" alt="Welcome to Saint Louis Christian College"></a></td>
  </tr>
</table>
</div>
</table>
