<table width="100%" height="37" border="0" align="center" cellpadding="0" cellspacing="0">
	<tr>
		<td bgcolor="#003974">
			<table height="37" border="0" cellpadding="0" cellspacing="0" align="center">
				<tr height="37">
					<td width="42" height="37"><img src="images/topleftcorner3_04.jpg" border="0" /></td>
					<td width="110" height="37" background="images/menutabs_05.gif"><a href="future_students/"><img src="images/admissions.gif" border="0" /></a></td>
					<td width="110" height="37" background="images/menutabs_09.gif"><a href="current_students/"><img src="images/academics.gif" width="110" border="0" /></a></td>
					<td width="110" height="37" background="images/menutabs_09.gif"><a href="alumni/"><img src="images/alumni.gif" width="110" border="0" /></a></td>
					<td width="110" height="37" background="images/menutabs_09.gif"><a href="athletics/"><img src="images/athletics.gif" width="110" border="0" /></a></td>
					<td width="110" height="37" background="images/menutabs_09.gif"><a href="bookstore/"><img src="images/bookstore.gif" width="110" border="0" /></a></td>
					<td width="110" height="37" background="images/menutabs_09.gif"><a href="giving/"><img src="images/giving.gif" width="110" border="0" /></a></td>
					<td width="110" height="37" background="images/menutabs_11.gif"><img src="images/search.gif" width="110" border="0" /></td>
					<td width="42" height="37"><img src="images/toprightcorner_12.jpg" border="0" /></td>
				</tr>
			</table>
		</td>
	</tr>
</table>